### ISSUE TITLE
The terraform-provider-conformity_v0.5.0 plugin crashed!

### ISSUE THREAD

**Issue by fogers777** [trendmicro/terraform-provider-conformity#60]
Hello,

we are getting an error when using conformity provider. It started happening today. Retry doesnt help.

TERRAFORM_VERSION: '1.4.6'
AWS_CLI_VERSION: '2.11.13'`

```
terraform plan \ # collapsed multi-line command
╷
│ Error: Plugin did not respond
│ 
│   with module.conformity[0].conformity_aws_account.aws,
│   on .terraform/modules/conformity/account.tf line 1, in resource "conformity_aws_account" "aws":
│    1: resource "conformity_aws_account" "aws" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
Stack trace from the terraform-provider-conformity_v0.5.0 plugin:
panic: interface conversion: interface {} is string, not map[string]interface {}
goroutine 54 [running]:
github.com/trendmicro/terraform-provider-conformity/conformity.flattenRuleValues({0xc00054e400, 0x1b, 0xbd6778})
	github.com/trendmicro/terraform-provider-conformity/conformity/account_settings.go:155 +0x427
github.com/trendmicro/terraform-provider-conformity/conformity.flattenExtraSettings({0xc000313f80, 0x1, 0xbdaf82})
	github.com/trendmicro/terraform-provider-conformity/conformity/account_settings.go:131 +0x391
github.com/trendmicro/terraform-provider-conformity/conformity.flattenSettings({0x1, {0xc0004dc990, 0xa}, {0xc0004dc988, 0x4}, 0x0, {0xc000313f80, 0x1, 0x4}, 0xc0005f1d10})
	github.com/trendmicro/terraform-provider-conformity/conformity/account_settings.go:87 +0x395
github.com/trendmicro/terraform-provider-conformity/conformity.flattenRuleSettings({0xc0004d6f00, 0x2, 0xbd520d})
	github.com/trendmicro/terraform-provider-conformity/conformity/account_settings.go:32 +0x1b8
github.com/trendmicro/terraform-provider-conformity/conformity.flattenAccountSettings(0xc000[35]
	github.com/trendmicro/terraform-provider-conformity/conformity/account_settings.go:20 +0xd9
github.com/trendmicro/terraform-provider-conformity/conformity.resourceAwsAccountRead({0xcde960, 0xc00021ecf0}, 0xc00021c080, {0xbcca20, 0xc000402600})
	github.com/trendmicro/terraform-provider-conformity/conformity/resource_aws_account.go:165 +0x406
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0000df260, {0xcde960, 0xc00021ecf0}, 0xd, {0xbcca20, 0xc000402600})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0000df260, {0xcde960, 0xc00021ecf0}, 0xc00032de10, {0xbcca20, 0xc000402600})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0002843a8, {0xcde8b8, 0xc000403100}, 0xc000403180)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:613 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0001b55e0, {0xcde960, 0xc00050bef0}, 0xc000[36]
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:746 +0x48c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xbac340, 0xc0001b55e0}, {0xcde960, 0xc00050bef0}, 0xc000361020, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fe8c0, {0xceb8e8, 0xc000308820}, 0xc0000c6c60, 0xc000293ec0, 0x11b4dd0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0001fe8c0, {0xceb8e8, 0xc000308820}, 0xc0000c6c60, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x294
Error: The terraform-provider-conformity_v0.5.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

our terraform code:

```
resource "conformity_aws_account" "aws" {
  name        = var.name
  environment = var.environment
  role_arn    = aws_cloudformation_stack.cloud-conformity.outputs["CloudConformityRoleArn"]
  external_id = data.conformity_external_id.external.external_id
  tags        = var.tags

  settings {

    rule {
      rule_id = "S3-021"
      settings {
        enabled     = false
        risk_level  = "HIGH"
        rule_exists = false
      }
    }
  }
}

resource "conformity_communication_setting" "email_setting" {

  email {
    users = ["urn:cloudone:identity:us-1:111111111111:user/*********-*****-*****-***-********"]
  }

  filter {
    risk_levels = ["HIGH", "VERY_HIGH", "EXTREME"]
  }

  relationships {
    account {
      id = resource.conformity_aws_account.aws.id
    }
    organisation {
      id = "11111111111"
    }
  }
}

resource "conformity_report_config" "report" {
  count = var.conformity_report_enabled ? 1 : 0 

  configuration {
    title                    = "Cloud Conformity Report for AWS Accounts"
    emails                   = ["email@email.com"]
    send_email               = true
    scheduled                = true
    frequency                = "* * 1" # every monday
    should_email_include_csv = true
    should_email_include_pdf = true
    include_account_names    = false
    tz                       = "US/Eastern"
  }

  filter {
    providers              = ["aws"]
    risk_levels            = ["HIGH", "VERY_HIGH", "EXTREME"]
    suppressed             = false
    suppressed_filter_mode = "v1"
    statuses               = ["FAILURE"]
  }
}
```

**Comment by johan1252** [comment]
Hi, thanks for reporting the issue.

To help debug what may be happening, did you happen to recently add/change the `settings` field in `conformity_aws_account` resource:
```
settings {

    rule {
      rule_id = "S3-021"
      settings {
        enabled     = false
        risk_level  = "HIGH"
        rule_exists = false
      }
    }
  }
```

**Comment by johan1252** [comment]
Hi,

Thanks for reporting this issue!
We have looked into it and it appears to happen if certain rules with special "values" field in "extraSetting" are configured.
In this case it appears you have configured `Config-001` rule with some disabled regions which is causing the issue.

We will make an update to the Terraform provider to handle this case.
In the mean time, workaround is to not configure rule settings for `Config-001` rule.

**Comment by saayamori** [comment]
Hi,

Thank you for waiting.
There's [a new version v0.5.1](https://github.com/trendmicro/terraform-provider-conformity/releases/tag/v0.5.1) released to solve this issue. By using this version, there should be no crash occur when that `Config-001` rule is configured in the account.
